import '../models/user.dart';

final users = [
  User(
    id: 1,
    name: "Salvador R. Barron",
    email: "SalvadorRBarron@teleworm.us",
    balance: 2000,
    phone: "+1 918-299-0453",
    occupation: "Pest control worker at Bennett Brothers",
  ),
  User(
    id: 2,
    name: "Aaron S. Bird",
    email: "AaronSBird@jourrapide.com",
    balance: 5000,
    phone: "+1 508-625-9203",
    occupation: "Telecommunications equipment installer at Total Sources",
  ),
  User(
    id: 3,
    name: "Robert R. Burton",
    email: "RobertRBurton@jourrapide.com",
    balance: 60000,
    phone: "+1 909-810-9102",
    occupation: "Scientific photographer at Kleinhans",
  ),
  User(
    id: 4,
    name: "Samuel S. Acheson",
    email: "SamuelSAcheson@dayrep.com",
    balance: 15450,
    phone: "+1 773-965-4104",
    occupation: "Greenhouse worker at J. Brannam",
  ),
  User(
    id: 5,
    name: "Lewis B. East",
    email: "LewisBEast@dayrep.com",
    balance: 6500,
    phone: "+1 901-213-4081",
    occupation: "Reactor operator at Trak Auto",
  ),
  User(
    id: 6,
    name: "Danny A. Edwards",
    email: "DannyAEdwards@rhyta.com",
    balance: 30000,
    phone: "+1 423-396-3692",
    occupation: "Foot doctor at Luria's",
  ),
  User(
    id: 7,
    name: "Tammara A. Best",
    email: "TammaraABest@jourrapide.com",
    balance: 12000,
    phone: "+1 985-219-3647",
    occupation:
        "Compensation and benefits technician at Lawn N' Order Garden Care",
  ),
  User(
    id: 8,
    name: "Elsie P. Davidson",
    email: "ElsiePDavidson@armyspy.com",
    balance: 4500,
    phone: "+1 248-918-1168",
    occupation: "Research dietitian at Universo Realtors",
  ),
  User(
    id: 9,
    name: "Margaret G. Priestley",
    email: "MargaretGPriestley@dayrep.com",
    balance: 450,
    phone: "+1 216-987-4675",
    occupation: "Personal and home care aide at Endicott Johnson",
  ),
  User(
    id: 10,
    name: "Doris D. Penn",
    email: "DorisDPenn@dayrep.com",
    balance: 1000,
    phone: "+1 216-410-2588",
    occupation: "Bindery worker at Susie's Casuals",
  ),
];
